apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      dnsPolicy: ClusterFirst  # Ensure correct DNS settings
      containers:
        - name: frontend
          image: registry.digitalocean.com/ssl-checker-registry/ssl-checker-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: "http://backend-service.backend.svc.cluster.local:5000"  # Inject backend URL into the environment
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "4eb12c9c-c6ba-4cf9-bdf8-d185c9c1b6aa"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 443
      targetPort: 80 #Nginx is running on port 80
  type: LoadBalancer

